version: '3.7'
services:

  motioneye:
    image: ccrisan/motioneye:master-armhf
    container_name: motioneye
    hostname: motioneye
    restart: always
    ports:
      - "8081:8081"
      - "8765:8765"
    environment:
      - TZ=Europe/Brussels
      - PUID=0
      - PGID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./motioneye/config:/etc/motioneye
      - ./motioneye/pictures:/var/lib/motioneye/Camera1
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/video0:/dev/video0

  dht-to-mqtt:
    image: mistercaste/dht-to-mqtt:1.0.1
    container_name: dht-to-mqtt
    network_mode: host
    privileged: true
    restart: always
    environment:
      - MQTT_HOSTNAME=nas.home
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}

  bmp085-to-mqtt:
    image: mistercaste/bmp085-to-mqtt:1.0.1
    container_name: bmp085-to-mqtt
    network_mode: host
    privileged: true
    restart: always
    environment:
      - MQTT_HOSTNAME=nas.home
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.35.3
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Brussels
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_4037dbdef88bed11a1687d7937e930e3-if00-port0:/dev/ttyACM0
