services:

  motioneye:
    image: ccrisan/motioneye:master-armhf
    container_name: motioneye
    hostname: motioneye
    restart: always
    ports:
      - "8081:8081"
      - "8765:8765"
    environment:
      - TZ=Europe/Brussels
      - PUID=0
      - PGID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./motioneye/config:/etc/motioneye
      - ./motioneye/pictures:/var/lib/motioneye/Camera1
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/video0:/dev/video0

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: always
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Brussels
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_4037dbdef88bed11a1687d7937e930e3-if00-port0:/dev/ttyACM0

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
